---
- name: Prepare directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
  - "{{ acme_paths['install_path'] }}"
  - "{{ acme_paths['cert_path'] }}"
  - "{{ acme_paths['download_path'] }}"

- name: Install prerequisites
  package:
    name: "{{ acme_prerequisite_packages }}"
    state: present

- name: Clone acme.sh
  git:
    dest: "{{ acme_paths['download_path'] }}"
    repo: https://github.com/acmesh-official/acme.sh
    version: "3.0.4"
    update: true
    force: true

- name: Check if the acme.sh directory is present
  stat:
    path: "{{ acme_paths['install_path'] }}/acme.sh"
  register: acme_install_path

- name: Install acme.sh
  command: ./acme.sh --install --nocron --home "{{ acme_paths['install_path'] }}" --certhome "{{ acme_paths['cert_path'] }}" --accountemail "{{ acme_account_email }}" chdir="{{ acme_paths['download_path'] }}"
  when: not acme_install_path.stat.exists

- name: Make sure the ACME server is set to {{ acme_server }}
  command: "./acme.sh --home {{ acme_paths['install_path'] }} --set-default-ca  --server {{ acme_server }}"
  changed_when: false

- name: Upgrade acme.sh
  command: ./acme.sh --upgrade --nocron --home "{{ acme_paths['install_path'] }}" --certhome "{{ acme_paths['cert_path'] }}" --accountemail "{{ acme_account_email }}" chdir="{{ acme_paths['download_path'] }}"
  changed_when: false
  when: acme_install_path.stat.exists

- name: Create cron job
  cron:
    name: Acme.sh certificate renew
    minute: '0'
    hour: '2'
    user: root
    job: "{{ acme_paths['install_path'] }}/acme.sh --cron --home {{ acme_paths['install_path'] }} >> {{ acme_paths['log_file'] }}"
  when: acme_install_path.stat.exists
